name: quickjs
description: A dart binding of quickjs, a powerful js engine with native_assets_cli.
version: 1.0.0
repository: https://github.com/lindeer/quickjs-dart

topics:
  - js

environment:
  sdk: ^3.3.0

dependencies:
  ffi: ^2.1.0
  native_assets_cli: ^0.5.4

dev_dependencies:
  ffigen: ^11.0.0
  lints: ^3.0.0
  test: ^1.24.0
