name: quickjs
description: A dart binding of quickjs, a powerful js engine with native_assets_cli.
version: 1.0.0
repository: https://github.com/lindeer/quickjs-dart

environment:
  sdk: ^3.3.0

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
